// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    var doStuffWithPhotos, init;

    doStuffWithPhotos = function(photos) {
      return $.each(photos, function(index, photo) {
        var photoImage, photoURL;

        console.log(index);
        console.log(photo);
        console.log('-------');
        photoURL = photo.image_url;
        photoImage = "<img src=\" " + photoURL + "\"/>";
        return $('#photos').append(photoImage);
      });
    };
    init = function() {
      _500px.init({
        sdk_key: 'e4671f3b61a876dfe887c5031b43d3dd900b63ce'
      });
      return _500px.api("/photos", {
        feature: 'popular',
        image_size: 440,
        page: 1
      }, function(response) {
        return doStuffWithPhotos(response.data.photos);
      });
    };
    return init();
  });

}).call(this);
